name: tbls

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - run: sudo systemctl start mysql.service
      - run: mysql -uroot -h127.0.0.1 -proot -e 'CREATE DATABASE IF NOT EXISTS test;'
      - run: mysql -uroot -h127.0.0.1 -proot test < ./test.sql

      - name: Install tbls
        run: curl -L https://git.io/dpkg-i-from-url | bash -s -- https://github.com/k1LoW/tbls/releases/download/v$TBLS_VERSION/tbls_$TBLS_VERSION-1_amd64.deb
        env:
          TBLS_VERSION: 1.49.7
      - run: tbls doc --force mysql://root:root@127.0.0.1:3306/test

      - name: Count files with changes
        id: file_count
        run: |
          git add -N dbdoc
          echo "::set-output name=count::$(git diff --name-only | wc -l)"

      - name: Commit
        run: |
          git config --global user.email "abe@enzou.tokyo"
          git config --global user.name "test"
          git add dbdoc
          git commit -m 'docs: add the document generated by tbls'
          git push origin master
        if: steps.file_count.outputs.count > 0
